name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to reg.mrkal.fi
      uses: docker/login-action@v2
      with:
        registry: reg.mrkal.fi
        username: ${{ secrets.reg_mr_user }}
        password: ${{ secrets.reg_mr_password }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: reg.mrkal.fi/mrkalfi:latest
    - name: Update container on server
      run: curl -d '{"username"="test", "content"="hello"}' ${{ secrets.reg_webhook }}
